"""Recognition: is this goal already a lemma somebody wrote?

The prover's failures are overwhelmingly REACH failures. `putnam_2020_a2`
died on a Pascal reindexing that `Finset.sum_range_succ'` performs
directly; `aux_odd_choose_lower_half` was reinvented and proved from
scratch when it is `Nat.sum_range_choose_halfway`. Existing retrieval
cannot help — `premise_retrieval.retrieve_bm25` indexes declaration NAMES,
which answers "what is CALLED something like this", never "what STATES
this".

Every test below pins a defect that was live in the first version of this
module and would have made it useless or dishonest:

* names were stored UNQUALIFIED (83% of Mathlib), so `confirm` would have
  compiled `exact choose_succ_succ` and failed on every candidate;
* statements were truncated at the `:=` inside `@[to_additive (attr :=
  simp)]`, corrupting ~2,900 declarations;
* `Finset.sum_range_succ'` — the lemma the motivating problem needed —
  is GENERATED by `@[to_additive]` and appears in no source file;
* numerals were not tokenized, so `4 ^ k` and `2 ^ n` looked identical
  and the right lemma ranked below unrelated ones;
* a goal of pure symbols (`|a + b| ≤ |a| + |b|`) tokenized to ONE token;
* `confirm` emitted its own `import` line, which the pipeline's verifier
  would have placed after a declaration — a syntax error every time.

The soundness contract: retrieval only RANKS. Nothing is usable until
Lean accepts it, so a wrong suggestion costs one compile and can never
enter a proof.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from search.recognize import (                                  # noqa: E402
    Candidate, Recognition, StatementIndex, additive_name,
    additive_statement, candidate_tactics, confirm, confirm_tactic,
    extract_declarations, recognize, tokenize,
)


def _names(decls):
    return [d["name"] for d in decls]


# ---- extraction: qualified names --------------------------------------------

def test_declaration_inside_a_namespace_is_fully_qualified():
    """`confirm` compiles `exact <name>`; a bare name does not resolve."""
    src = ("namespace Nat\n\n"
           "theorem choose_succ_succ (n k : ℕ) : choose n k = 0\n\n"
           "end Nat\n")
    assert _names(extract_declarations(src, "M")) == ["Nat.choose_succ_succ"]


def test_nested_namespaces_compose():
    src = ("namespace Foo\nnamespace Bar\n"
           "theorem baz (n : ℕ) : n = n\n"
           "end Bar\nend Foo\n")
    assert _names(extract_declarations(src, "M")) == ["Foo.Bar.baz"]


def test_dotted_namespace_declaration():
    src = "namespace Foo.Bar\ntheorem baz (n : ℕ) : n = n\nend Foo.Bar\n"
    assert _names(extract_declarations(src, "M")) == ["Foo.Bar.baz"]


def test_end_closes_the_namespace():
    src = ("namespace Foo\ntheorem a (n : ℕ) : n = n\nend Foo\n"
           "theorem b (n : ℕ) : n = n\n")
    assert _names(extract_declarations(src, "M")) == ["Foo.a", "b"]


def test_section_does_not_contribute_to_names():
    """`section` closes with `end` too, but names nothing."""
    src = ("namespace Foo\nsection Bar\n"
           "theorem baz (n : ℕ) : n = n\n"
           "end Bar\nend Foo\n")
    assert _names(extract_declarations(src, "M")) == ["Foo.baz"]


def test_already_dotted_name_keeps_its_own_prefix():
    src = "namespace Foo\ntheorem Bar.baz (n : ℕ) : n = n\nend Foo\n"
    assert _names(extract_declarations(src, "M")) == ["Foo.Bar.baz"]


# ---- extraction: the statement ----------------------------------------------

def test_attribute_containing_assignment_does_not_truncate_the_statement():
    """`@[to_additive (attr := simp)]` cut every such statement to
    `@[to_additive (attr`."""
    src = ("@[to_additive (attr := simp)]\n"
           "theorem prod_congr (s : Finset a) : ∏ x ∈ s, f x = 1 := by\n"
           "  simp\n")
    d = extract_declarations(src, "M")[0]
    assert "attr" not in d["statement"]
    assert d["statement"].startswith("theorem prod_congr")
    assert "∏ x ∈ s, f x = 1" in d["statement"]


def test_statement_stops_at_the_body():
    src = "theorem foo (n : ℕ) : n = n := by\n  simp [bar_baz_qux]\n"
    assert "bar_baz_qux" not in extract_declarations(src, "M")[0]["statement"]


def test_equation_style_body_is_not_absorbed_into_the_statement():
    """An equation-style declaration has NO `:=` anywhere, so the whole
    proof was stored as part of the statement. That is not just noise: it
    doubles the document length, and BM25 length normalisation then ranks
    a perfect-overlap statement BELOW partial matches.
    `Finset.sum_range_succ'` — the lemma this module exists to find — was
    invisible for exactly this reason while sharing every query token."""
    src = ("theorem prod_range_succ' (f : ℕ → M) :\n"
           "    ∀ n : ℕ, (∏ k ∈ range (n + 1), f k) = 1\n"
           "  | 0 => prod_range_zero _\n"
           "  | n + 1 => by rw [mul_right_comm]\n")
    stmt = extract_declarations(src, "M")[0]["statement"]
    assert "mul_right_comm" not in stmt
    assert "prod_range_zero" not in stmt
    assert stmt.endswith("= 1")


# ---- @[to_additive] ---------------------------------------------------------

def test_bare_to_additive_synthesises_the_twin():
    """`Finset.sum_range_succ'` exists in NO source file."""
    src = ("namespace Finset\n@[to_additive]\n"
           "theorem prod_range_succ' (f : ℕ → M) (n : ℕ) :\n"
           "    (∏ k ∈ range (n + 1), f k) = 1\nend Finset\n")
    decls = extract_declarations(src, "M")
    assert "Finset.sum_range_succ'" in _names(decls)
    twin = [d for d in decls if d.get("synthetic")][0]
    assert "∑" in twin["statement"] and "∏" not in twin["statement"]


def test_twin_is_flagged_and_the_original_is_not():
    src = "@[to_additive]\ntheorem prod_foo (n : ℕ) : n = n\n"
    decls = extract_declarations(src, "M")
    assert [d.get("synthetic", False) for d in decls] == [False, True]


def test_explicit_twin_name_is_honoured():
    src = "@[to_additive my_add_thing]\ntheorem my_mul_thing (n : ℕ) : n = n\n"
    assert "my_add_thing" in _names(extract_declarations(src, "M"))


def test_existing_keyword_is_not_a_name():
    src = "@[to_additive existing]\ntheorem prod_foo (n : ℕ) : n = n\n"
    assert "sum_foo" in _names(extract_declarations(src, "M"))


def test_to_additive_inside_a_longer_attribute_list():
    src = "@[simp, to_additive]\ntheorem prod_foo (n : ℕ) : n = n\n"
    assert "sum_foo" in _names(extract_declarations(src, "M"))


def test_declaration_without_to_additive_gets_no_twin():
    src = "@[simp]\ntheorem prod_foo (n : ℕ) : n = n\n"
    assert len(extract_declarations(src, "M")) == 1


def test_multiplicative_prefix_is_translated():
    """`mabs_mul_three` produced `mabs_add_three`, a name that exists
    nowhere; Mathlib's twin is `abs_add_three`."""
    assert additive_name("mabs_mul_three") == "abs_add_three"


def test_additive_name_keeps_primes_and_namespaces():
    assert additive_name("Finset.prod_range_succ'") == "Finset.sum_range_succ'"


def test_additive_statement_rewrites_symbols():
    assert additive_statement("∏ x ∈ s, f x * g x") == "∑ x ∈ s, f x + g x"


def test_additive_statement_leaves_numerals_alone():
    """The multiplicative identity is written `1`, but so is the Nat
    literal in `range (n + 1)`. Rewriting `1`→`0` would turn the very
    lemma this module exists to find into `range (n + 0)`. Retrieval
    tolerates a stale `1`; it cannot tolerate a corrupted index."""
    out = additive_statement("∏ k ∈ range (n + 1), f k")
    assert out == "∑ k ∈ range (n + 1), f k"


def test_twin_statement_carries_the_twin_name():
    src = "@[to_additive]\ntheorem prod_foo (n : ℕ) : n = n\n"
    twin = [d for d in extract_declarations(src, "M") if d.get("synthetic")][0]
    assert "sum_foo" in twin["statement"]
    assert "prod_foo" not in twin["statement"]


# ---- tokenization -----------------------------------------------------------

def test_numerals_are_tokens():
    """`= 4 ^ k` vs `= 2 ^ n` is the whole difference between
    `sum_range_choose_halfway` and `sum_range_choose`."""
    assert "4" in tokenize("f = 4 ^ k")


def test_single_letters_are_dropped():
    """Bound-variable names say nothing about what a lemma states."""
    assert tokenize("n m k") == []


def test_namespace_and_snake_case_components_are_split():
    toks = tokenize("Finset.sum_range_succ")
    for part in ("Finset", "sum", "range", "succ"):
        assert part in toks


def test_symbolic_goal_does_not_tokenize_to_nothing():
    """`|a + b| ≤ |a| + |b|` reduced to the single token `≤` and
    retrieved unrelated graph lemmas."""
    assert len(set(tokenize("|a + b| ≤ |a| + |b|"))) >= 3


# ---- retrieval --------------------------------------------------------------

def _index():
    return StatementIndex([
        {"name": "Nat.sum_range_choose_halfway", "kind": "theorem",
         "module": "M",
         "statement": "theorem sum_range_choose_halfway (m : ℕ) : "
                      "(∑ i ∈ range (m + 1), (2 * m + 1).choose i) = 4 ^ m"},
        {"name": "Nat.sum_range_choose", "kind": "theorem", "module": "M",
         "statement": "theorem sum_range_choose (n : ℕ) : "
                      "(∑ m ∈ range (n + 1), n.choose m) = 2 ^ n"},
        {"name": "Nat.choose_self", "kind": "theorem", "module": "M",
         "statement": "theorem choose_self (n : ℕ) : choose n n = 1"},
        {"name": "Foo.bar", "kind": "def", "module": "M",
         "statement": "def bar (n : ℕ) : ℕ"},
    ])


def test_search_ranks_on_what_a_lemma_states():
    idx = _index()
    hits = idx.search("∑ i ∈ Finset.range (k + 1), "
                      "Nat.choose (2 * k + 1) i = 4 ^ k", k=3)
    assert hits[0].name == "Nat.sum_range_choose_halfway"


def test_search_can_filter_by_kind():
    idx = _index()
    assert all(c.kind in ("theorem", "lemma")
               for c in idx.search("bar", k=5, kinds=("theorem", "lemma")))


def test_search_on_an_empty_query_is_empty():
    assert _index().search("", k=5) == []


def test_index_size_is_reported():
    assert len(_index()) == 4


# ---- confirmation: the kernel is the only oracle ----------------------------

class _V:
    def __init__(self, ok=False, boom=False):
        self.ok, self.boom = ok, boom
        self.calls: list[tuple[str, str]] = []

    def __call__(self, header, body):
        self.calls.append((header, body))
        if self.boom:
            raise RuntimeError("lake died")
        return {"ok": self.ok, "errors": None if self.ok else "error: no"}


def _cands(*names):
    return [Candidate(n, "theorem", "s", "M", 1.0) for n in names]


def test_confirmation_costs_exactly_one_compile():
    """A compile costs 100-900s here; one per candidate per tactic would
    be 32 compiles and could never run inside a real attempt."""
    v = _V(ok=True)
    confirm("n = n", _cands("a", "b", "c"), verify_fn=v)
    assert len(v.calls) == 1


def test_confirm_emits_no_import_line():
    """The pipeline's verifier supplies imports; an import emitted here
    lands AFTER a declaration and fails on syntax, never on maths."""
    v = _V(ok=True)
    confirm("n = n", _cands("a"), verify_fn=v)
    header, _ = v.calls[0]
    assert "import" not in header
    assert header.startswith("example :")


def test_every_alternative_is_parenthesised():
    """An unparenthesised `first | ...` lets a trailing combinator swallow
    the next bar — the bug that broke the leaf-fallback ladder."""
    tac = confirm_tactic(_cands("a", "b"))
    for line in tac.splitlines()[1:]:
        assert line.strip().startswith("| (") and line.strip().endswith(")")


def test_confirmed_tactic_mentions_every_candidate():
    tac = confirm_tactic(_cands("alpha", "beta"))
    assert "alpha" in tac and "beta" in tac


def test_candidate_is_tried_more_than_one_way():
    """A retrieved lemma often matches only up to implicit arguments."""
    assert len(candidate_tactics("foo")) >= 3


def test_cheap_tactics_for_all_candidates_precede_expensive_ones():
    """Ordering is by COST ACROSS CANDIDATES, not grouped by candidate.

    Grouping by candidate buries a cheap `exact` on the fourth candidate
    behind nine `simpa`/`rw` elaborations on the first three. Measured:
    that ordering made the `putnam_2020_a2` reindexing goal hit a 1200s
    timeout with the correct lemma ranked FIRST — the kernel never got to
    answer. `first` commits to the earliest branch that closes the goal,
    so this cannot change which goals are provable, only how fast.
    """
    tac = confirm_tactic(_cands("a", "b", "c", "d"))
    lines = [ln.strip() for ln in tac.splitlines()[1:]]
    last_exact = max(i for i, ln in enumerate(lines) if "exact" in ln)
    first_slow = min(i for i, ln in enumerate(lines)
                     if "simpa" in ln or "rw [" in ln)
    assert last_exact < first_slow


def test_every_candidate_still_gets_every_form():
    tac = confirm_tactic(_cands("a", "b"))
    assert tac.count("(exact a)") == 1 and tac.count("(exact b)") == 1
    assert tac.count("(simpa using a)") == 1
    assert tac.count("(rw [b])") == 1


def test_rejected_candidates_yield_no_tactic():
    r = confirm("n = n", _cands("a"), verify_fn=_V(ok=False))
    assert r.confirmed is False and r.tactic == ""


# ---- a citation may need a step before it ----------------------------------
# Regression for `putnam_1986_b3`: the `h_cd` leaf
#   `∀ a b : Polynomial ℤ, ∀ m : ℤ, cong a b m ↔ Polynomial.C m ∣ a - b`
# is closed by Mathlib's `Polynomial.C_dvd_iff_dvd_coeff`. Retrieval RANKED
# it; confirmation reported `not_confirmed` because every form was a
# zero-step citation, and the run then spent ~1434 s of 2738 s abducing a
# replacement. Measured on that exact leaf: all four zero-step forms fail,
# `intros; simp only [*, {n}]` passes.


def test_a_form_exists_that_intros_the_binders():
    """A leaf goal is routinely `∀ …`; `rw` cannot reach under binders."""
    assert any("intros" in t for t in candidate_tactics("foo"))


def test_a_form_exists_that_uses_the_local_hypotheses():
    """PutnamBench states its predicates as hypothesis binders, not
    definitions. `simp only [*]` unfolds them BY CONTEXT — recognition
    can never know the hypothesis name, so a form naming one is useless."""
    tac = next(t for t in candidate_tactics("foo") if "intros" in t)
    assert "[*," in tac and "foo" in tac
    assert "hcong" not in tac, "must not hard-code a problem's hypothesis name"


def test_the_hypothesis_form_is_simp_only_not_simp():
    """Full `simp` FAILS the h_cd leaf where `simp only` passes — it
    normalises past the target — and costs more. Not an oversight."""
    tac = next(t for t in candidate_tactics("foo") if "intros" in t)
    assert "simp only [" in tac


def test_the_hypothesis_form_ends_in_done():
    """`first` backtracks on tactic FAILURE, never on unclosed goals, so
    every alternative must be all-or-nothing. `simp only [*, …]` is not:
    fed the WRONG candidate it still rewrites with the local hypotheses,
    succeeds with the goal open, and `first` commits to it — starving the
    right candidate further down the ladder. Observed on the h_cd leaf
    with `Polynomial.coeff_C_mul` ranked ahead of the correct lemma.
    `done` converts "made progress" back into failure."""
    tac = next(t for t in candidate_tactics("foo") if "intros" in t)
    assert tac.rstrip().endswith("done")


def test_every_alternative_is_all_or_nothing():
    """The ladder invariant, stated over the whole form set rather than
    the one form that currently violates it by construction."""
    for tac in candidate_tactics("foo"):
        closing = (tac.startswith("exact ") or tac.startswith("simpa ")
                   or tac.startswith("rw [") or tac.rstrip().endswith("done"))
        assert closing, f"{tac!r} can succeed with goals left open"


def test_the_hypothesis_form_is_ordered_last():
    """`confirm_tactic` iterates forms outer / candidates inner, so a
    form's position IS its cost rank. `simp only [*, …]` is the dearest
    of the five; ahead of the `exact`s it would reintroduce the
    `putnam_2020_a2` timeout this ordering exists to prevent."""
    tac = confirm_tactic(_cands("a", "b", "c"))
    lines = [ln.strip() for ln in tac.splitlines()[1:]]
    first_hyp = min(i for i, ln in enumerate(lines) if "intros" in ln)
    assert first_hyp == len(lines) - 3, "all 3 must be the final block"
    assert all("intros" not in ln for ln in lines[:first_hyp])


def test_adding_the_form_did_not_disturb_the_cheap_ordering():
    """The `exact`-before-`simpa`/`rw` guarantee is independent of it."""
    tac = confirm_tactic(_cands("a", "b", "c", "d"))
    lines = [ln.strip() for ln in tac.splitlines()[1:]]
    last_exact = max(i for i, ln in enumerate(lines) if "exact" in ln)
    first_slow = min(i for i, ln in enumerate(lines)
                     if "simpa" in ln or "rw [" in ln)
    assert last_exact < first_slow


def test_the_hypothesis_form_is_still_parenthesised():
    """It contains `;` — an unparenthesised alternative would let the
    sequencing swallow the following bar."""
    tac = confirm_tactic(_cands("a"))
    hyp = [ln.strip() for ln in tac.splitlines()[1:] if "intros" in ln]
    assert hyp and all(ln.startswith("| (") and ln.endswith(")") for ln in hyp)


def test_accepted_candidates_yield_a_usable_tactic():
    r = confirm("n = n", _cands("a"), verify_fn=_V(ok=True))
    assert r.confirmed and "exact a" in r.tactic


def test_verifier_failure_is_survivable():
    r = confirm("n = n", _cands("a"), verify_fn=_V(boom=True))
    assert r.confirmed is False


def test_no_candidates_costs_no_compile():
    v = _V(ok=True)
    r = confirm("n = n", [], verify_fn=v)
    assert r.confirmed is False and v.calls == []


# ---- the recognize contract -------------------------------------------------

def test_recognize_without_a_verifier_confirms_nothing():
    """An unconfirmed name is exactly what has already cost whole runs."""
    r = recognize("∑ i ∈ range (k+1), choose i = 4 ^ k", _index())
    assert isinstance(r, Recognition)
    assert r.confirmed is False and r.tactic == ""
    assert r.candidates                      # it still retrieved


def test_recognize_confirms_through_the_kernel():
    v = _V(ok=True)
    r = recognize("∑ i ∈ range (k+1), choose i = 4 ^ k", _index(),
                  verify_fn=v)
    assert r.confirmed and len(v.calls) == 1


def test_recognize_reports_a_kernel_rejection_honestly():
    r = recognize("∑ i ∈ range (k+1), choose i = 4 ^ k", _index(),
                  verify_fn=_V(ok=False))
    assert r.confirmed is False


def test_recognize_traces_without_raising():
    events = []
    recognize("choose n n = 1", _index(), verify_fn=_V(ok=True),
              trace=lambda kind, **kw: events.append((kind, kw)))
    assert [k for k, _ in events] == ["recognize", "recognize"]
    assert events[-1][1]["stage"] == "CONFIRMED"


def test_tracing_is_optional():
    recognize("choose n n = 1", _index(), verify_fn=_V(ok=True), trace=None)
