"""Recognition: does this goal already exist in Mathlib?

The prover's failures are overwhelmingly *reach* failures, not knowledge
failures. On `putnam_2020_a2` the only hard step reduced to a Pascal
reindexing that `Finset.sum_range_succ'` performs directly; the model
never reached for it and burned its whole budget. On `putnam_2000_b2` the
blocking lemma was the absorption identity, which Mathlib carries. On
`putnam_2020_a2` again, `aux_odd_choose_lower_half` was reinvented and
proved from scratch when it is `Nat.sum_range_choose_halfway`.

Existing retrieval cannot fix this: `premise_retrieval.retrieve_bm25`
indexes declaration NAMES. A name index answers "what is called
something like this", never "what states this". This module indexes
STATEMENTS, so a goal can be matched against what a lemma says.

Soundness. Retrieval only RANKS. Candidates become usable only when Lean
accepts them, so a wrong suggestion can never mislead a proof. Same
one-directional contract as the refutation pass: it can supply or stay
silent, never assert.

Cost. The whole recognition step is ONE compile: every candidate, tried
every way, is combined into a single `first | …` tactic (the trick the
leaf portfolio already uses). At 100-900s per compile on this host, one
compile per candidate would not fit inside a real proof attempt.

Coverage. The index is built from every Lean source the pin puts on disk
— Mathlib, the sibling Lake packages, and the pinned toolchain's own core
— plus the `@[to_additive]` twins, which exist in the Lean environment
but in NO source file. That last part is not an optimisation: the lemma
that would have unblocked `putnam_2020_a2`, `Finset.sum_range_succ'`, is
one of them.

Nothing here is problem-specific: everything is derived from the pin,
exactly like `decl_module_index`.
"""
from __future__ import annotations

import json
import math
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable

# Declaration heads worth indexing. `example` is excluded: unnamed and
# therefore uncitable.
_KINDS = ("theorem", "lemma", "def", "abbrev", "instance", "structure",
          "class")
_DECL_RE = re.compile(
    r"(?m)^(?P<attrs>(?:@\[[^\]]*\]\s*)*)"
    r"(?:private\s+|protected\s+|noncomputable\s+|partial\s+|unsafe\s+)*"
    r"(?P<kind>" + "|".join(_KINDS) + r")\s+"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_'!?₀-₉.]*)")
_BLOCK_COMMENT_RE = re.compile(r"/-.*?-/", re.S)
_LINE_COMMENT_RE = re.compile(r"--[^\n]*")

#: Namespace/section scoping. A name must be recorded FULLY QUALIFIED:
#: `confirm` compiles `exact <name>`, and inside `namespace Nat` the
#: source says `theorem choose_succ_succ` while the citable name is
#: `Nat.choose_succ_succ`. 83% of Mathlib declarations are written inside
#: a namespace, so storing the bare name makes almost every candidate
#: unresolvable — the recognizer would spend a compile per candidate and
#: never confirm anything.
#:
#: `section` also closes with `end`, but contributes NOTHING to names, so
#: both are tracked and only namespaces contribute a prefix.
_SCOPE_RE = re.compile(
    r"(?m)^\s*(?P<op>namespace|section|end)\b[ \t]*"
    r"(?P<name>[A-Za-z_][A-Za-z0-9_'₀-₉.]*)?")


def _strip_comments(text: str) -> str:
    return _LINE_COMMENT_RE.sub(" ", _BLOCK_COMMENT_RE.sub(" ", text))


# ---- @[to_additive] ---------------------------------------------------------
#
# `Finset.sum_range_succ'` — the lemma that performs the reindexing
# `putnam_2020_a2` died on — DOES NOT EXIST in Mathlib's source. It is
# generated by `@[to_additive]` from `Finset.prod_range_succ'`. There are
# 15,197 such attributes, and the additive twins are disproportionately the
# `∑` lemmas competition problems need, so a source-text index is blind to
# exactly the wrong half of Mathlib.
#
# The twins are therefore SYNTHESISED: the multiplicative name and
# statement are rewritten through Mathlib's naming dictionary. This is an
# APPROXIMATION — Mathlib's real translation is type-directed and reorders
# some names (`pow_succ` ↦ `succ_nsmul`), which a dictionary cannot do.
# That is acceptable here and nowhere else, because retrieval only ranks:
# a wrongly synthesised name costs ONE compile in `confirm` and can never
# enter a proof. Synthesised records are flagged `synthetic: true` so they
# are never mistaken for observed source.

_TO_ADDITIVE_RE = re.compile(r"@\[(?P<body>[^\]]*)\]")
#: Keywords that may follow `to_additive` without naming the twin.
_TA_KEYWORDS = {"existing", "self", "reorder", "attr", "dont_translate"}

#: Order is irrelevant: names are translated component-by-component after
#: splitting on `_`, and statements are rewritten under word boundaries,
#: so `pow` cannot match inside `npow`.
_ADDITIVE_WORDS = {
    # Multiplicative-first heads whose twin DROPS or rewrites the prefix.
    # Missing `mabs` produced the name `mabs_add_three` from the real
    # `mabs_mul_three`, when Mathlib's twin is `abs_add_three` — a
    # half-translated name that exists nowhere.
    "mabs": "abs", "mulIndicator": "indicator", "mulSupport": "support",
    "mulTSupport": "tsupport", "mulEnergy": "addEnergy",
    "orderOf": "addOrderOf", "IsOfFinOrder": "IsOfFinAddOrder",
    "mulAntidiagonal": "addAntidiagonal", "mulRothNumber": "addRothNumber",
    "prod": "sum", "mul": "add", "one": "zero", "inv": "neg", "div": "sub",
    "npow": "nsmul", "zpow": "zsmul", "pow": "smul", "monoid": "addMonoid",
    "Monoid": "AddMonoid", "group": "addGroup", "Group": "AddGroup",
    "Submonoid": "AddSubmonoid", "Subgroup": "AddSubgroup",
    "Multiplicative": "Additive", "units": "addUnits", "Units": "AddUnits",
    "MonoidHom": "AddMonoidHom", "isUnit": "isAddUnit",
}
_ADDITIVE_SYMBOLS = {"∏": "∑", "*": "+", "⁻¹": "-", "/": "-"}


def _to_additive_clause(attrs: str) -> str | None:
    """The `to_additive …` clause of an attribute block, if present."""
    for m in _TO_ADDITIVE_RE.finditer(attrs or ""):
        depth, cur, items = 0, [], []
        for ch in m.group("body"):
            if ch in "([{":
                depth += 1
            elif ch in ")]}":
                depth -= 1
            if ch == "," and depth == 0:
                items.append("".join(cur))
                cur = []
            else:
                cur.append(ch)
        items.append("".join(cur))
        for it in items:
            it = it.strip()
            if it == "to_additive" or it.startswith("to_additive "):
                return it
    return None


def _explicit_additive_name(clause: str) -> str | None:
    """The twin's name when the attribute states it outright."""
    rest = clause[len("to_additive"):].strip().lstrip("?").strip()
    rest = re.sub(r"\([^)]*\)", " ", rest)              # drop (attr := …)
    rest = re.sub(r'"[^"]*"', " ", rest)                # drop docstrings
    for tok in rest.split():
        tok = tok.strip(",")
        if not tok or tok in _TA_KEYWORDS:
            continue
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_'₀-₉.]*", tok):
            return tok
        return None
    return None


def additive_name(name: str) -> str:
    """Translate a multiplicative declaration name to its additive twin."""
    head, _, base = name.rpartition(".")
    parts = base.split("_")
    out = []
    for p in parts:
        core = p.rstrip("'!?")
        tail = p[len(core):]
        out.append(_ADDITIVE_WORDS.get(core, core) + tail)
    new = "_".join(out)
    if head:
        head = ".".join(_ADDITIVE_WORDS.get(h, h) for h in head.split("."))
        return f"{head}.{new}"
    return new


def additive_statement(stmt: str) -> str:
    """Rewrite a statement for RETRIEVAL only — never emitted as Lean."""
    for a, b in _ADDITIVE_SYMBOLS.items():
        stmt = stmt.replace(a, b)
    for a, b in _ADDITIVE_WORDS.items():
        stmt = re.sub(rf"(?<![A-Za-z0-9_]){re.escape(a)}(?![A-Za-z0-9_])",
                      b, stmt)
    return stmt


def _scope_events(clean: str) -> list[tuple[int, str]]:
    """[(offset, namespace_prefix)] — the prefix in force from that offset."""
    stack: list[tuple[str, str]] = []          # (op, name)
    events: list[tuple[int, str]] = [(0, "")]
    for m in _SCOPE_RE.finditer(clean):
        op, name = m.group("op"), m.group("name")
        if op == "end":
            # `end` closes the innermost matching scope; an unnamed `end`
            # closes the innermost scope of any kind.
            for i in range(len(stack) - 1, -1, -1):
                if name is None or stack[i][1] == name:
                    del stack[i:]
                    break
            else:
                if stack:
                    stack.pop()
        else:
            if op == "section" and name is None:
                stack.append(("section", ""))
                continue
            if name is None:
                continue
            stack.append((op, name))
        prefix = ".".join(n for k, n in stack if k == "namespace" and n)
        events.append((m.end(), prefix))
    return events


def _cut_body(chunk: str) -> str:
    """Drop the proof, keeping binders and conclusion.

    `:=` is not the only body marker. An EQUATION-STYLE declaration —

        theorem prod_range_succ' (f : ℕ → M) :
            ∀ n : ℕ, (∏ k ∈ range (n + 1), f k) = …
          | 0 => prod_range_succ _ _
          | n + 1 => by rw [prod_range_succ _ n, …]

    has no `:=` anywhere, so the whole proof was absorbed into the
    statement. That does not merely add noise: it doubles the document
    length, and BM25's length normalisation then ranks a PERFECT-overlap
    statement below partial matches. `Finset.sum_range_succ'` — the lemma
    this module was written to find — was invisible for exactly this
    reason while sharing every one of the query's tokens.
    """
    for stop in (":=", "\nwhere", " where\n"):
        j = chunk.find(stop)
        if j != -1:
            chunk = chunk[:j]
    lines = chunk.split("\n")
    for i, ln in enumerate(lines):
        if i and ln.lstrip().startswith("|"):
            return "\n".join(lines[:i])
    return chunk


def _prefix_at(events: list[tuple[int, str]], pos: int) -> str:
    lo, hi, best = 0, len(events) - 1, ""
    while lo <= hi:
        mid = (lo + hi) // 2
        if events[mid][0] <= pos:
            best = events[mid][1]
            lo = mid + 1
        else:
            hi = mid - 1
    return best


def extract_declarations(text: str, module: str) -> list[dict]:
    """(name, kind, statement, module) for each declaration in a source file.

    `name` is FULLY QUALIFIED — see `_SCOPE_RE`. The statement runs from
    the declaration keyword to the body marker (`:=`, `where`) or the next
    declaration — i.e. binders and conclusion, which is what a goal must
    be matched against.
    """
    clean = _strip_comments(text)
    events = _scope_events(clean)
    out: list[dict] = []
    marks = list(_DECL_RE.finditer(clean))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(clean)
        # Start at the KEYWORD, not the attributes: `@[to_additive (attr
        # := simp)]` contains `:=`, and cutting the body at the first `:=`
        # truncated every such statement to `@[to_additive (attr`.
        # Attributes are noise for retrieval anyway.
        chunk = _cut_body(clean[m.start("kind"):end])
        stmt = " ".join(chunk.split())
        if len(stmt) < 8 or len(stmt) > 2000:
            continue
        prefix = _prefix_at(events, m.start())
        name = m.group("name")
        kind = m.group("kind")
        qual = f"{prefix}.{name}" if prefix else name
        out.append({"name": qual, "kind": kind,
                    "statement": stmt, "module": module})

        clause = _to_additive_clause(m.group("attrs"))
        if clause is None:
            continue
        explicit = _explicit_additive_name(clause)
        twin = explicit or additive_name(name)
        twin_qual = (twin if "." in twin
                     else (f"{prefix}.{twin}" if prefix else twin))
        if twin_qual == qual:
            continue
        # The statement still opens `theorem prod_range_succ …`; the
        # dictionary cannot rewrite that (the `_` blocks a word-boundary
        # match), so the twin's own name is substituted directly.
        twin_stmt = additive_statement(
            stmt.replace(f"{kind} {name}", f"{kind} {twin.rpartition('.')[2]}",
                         1))
        out.append({"name": twin_qual, "kind": kind,
                    "statement": twin_stmt,
                    "module": module, "synthetic": True})
    return out


def source_roots(project_root: str | Path) -> list[tuple[Path, str]]:
    """(directory, module-prefix) for every Lean source the pin makes
    available: Mathlib, the sibling Lake packages, and the pinned
    toolchain's own core sources.

    Mathlib alone is not enough. `abs_add` — the triangle inequality — is
    declared nowhere in `Mathlib/`, so a Mathlib-only index cannot
    recognise a goal that Lean proves with a one-liner. Core and Batteries
    carry a large share of the arithmetic and list lemmas competition
    proofs actually cite.
    """
    root = Path(project_root)
    roots: list[tuple[Path, str]] = []
    pkgs = root / "lean" / ".lake" / "packages"
    ml = pkgs / "mathlib" / "Mathlib"
    if ml.is_dir():
        roots.append((ml, "Mathlib."))
    for name in ("batteries", "plausible", "aesop", "Qq"):
        d = pkgs / name
        if d.is_dir():
            roots.append((d, ""))
    # The toolchain pinned in lean/lean-toolchain, never "whatever is newest".
    try:
        pin = (root / "lean" / "lean-toolchain").read_text(
            encoding="utf-8").strip()
        ver = pin.split(":", 1)[1] if ":" in pin else pin
        core = (Path.home() / ".elan" / "toolchains"
                / f"leanprover--lean4---{ver}" / "src" / "lean")
        if core.is_dir():
            roots.append((core, ""))
    except Exception:
        pass
    return roots


def build_index(roots: str | Path | Iterable[tuple[Path, str]],
                out_path: str | Path,
                progress: Callable[[int, int], None] | None = None) -> int:
    """Walk Lean sources and write a statement index.

    Derived entirely from what is on disk — no network, no model. Accepts
    a single directory (indexed with no module prefix) or the
    `(directory, prefix)` pairs from `source_roots`.
    """
    if isinstance(roots, (str, Path)):
        pairs = [(Path(roots), "")]
    else:
        pairs = [(Path(d), p) for d, p in roots]
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    n = 0
    seen: set[tuple[str, str]] = set()
    with out.open("w", encoding="utf-8") as fh:
        for base, prefix in pairs:
            files = sorted(base.rglob("*.lean"))
            for i, f in enumerate(files):
                try:
                    text = f.read_text(encoding="utf-8", errors="replace")
                except Exception:
                    continue
                module = (f.relative_to(base).with_suffix("")
                          .as_posix().replace("/", "."))
                for d in extract_declarations(text, prefix + module):
                    key = (d["name"], d["statement"][:120])
                    if key in seen:
                        continue
                    seen.add(key)
                    fh.write(json.dumps(d, ensure_ascii=False) + "\n")
                    n += 1
                if progress and i % 500 == 0:
                    progress(i, len(files))
    return n


# ---- retrieval --------------------------------------------------------------

#: NUMERALS ARE TOKENS. Dropping them was a real defect: the query
#: `… (2*k+1).choose i = 4 ^ k` and `Nat.sum_range_choose_halfway`
#: (`… (2*m+1).choose i = 4 ^ m`) agree on `2`, `1`, `4`, and those
#: literals are exactly what distinguishes that lemma from
#: `sum_range_choose` (`… = 2 ^ n`). Without them the right lemma ranked
#: outside the top 4 on a query that should have matched it almost
#: exactly.
#: Operators are tokens too. A goal can consist almost ENTIRELY of them:
#: `|a + b| ≤ |a| + |b|` has no multi-letter identifier and no numeral, so
#: under an identifier-only tokenizer it reduced to the single token `≤`
#: and retrieved unrelated graph lemmas. The discriminating symbols here
#: are `|` and `^`-style markers, which are rare enough to carry real IDF;
#: the ubiquitous `+ * =` cost little and keep symbolic goals from
#: tokenizing to nothing.
_TOKEN_RE = re.compile(
    r"[A-Za-z_][A-Za-z0-9_']*|\d+"
    r"|⁻¹|[∑∏∫√∀∃¬∧∨→↔≤≥≠∈⊆⊂∣∪∩∅∞≡‖⌊⌋⌈⌉∘×!|^+*=/-]")

#: Tokens carried by nearly every statement — they cost time and add noise.
_STOP = {
    "theorem", "lemma", "def", "abbrev", "instance", "structure", "class",
    "forall", "fun", "let", "in", "with", "by", "at", "of", "the", "to",
    "Type", "Sort", "Prop", "inst", "self",
}


def tokenize(text: str) -> list[str]:
    """Identifier, numeral and operator tokens.

    Namespace and snake_case components are split out, so
    `Finset.sum_range_succ` also matches on `sum`, `range`, `succ` — a
    query written with `Nat.choose x y` still meets a statement written
    with `x.choose y`.

    SINGLE-LETTER identifiers are dropped: they are bound-variable names
    (`m`, `k`, `i`, `n`), carry no information about what a lemma SAYS,
    and are common enough to swamp the discriminating tokens.
    """
    toks: list[str] = []
    for t in _TOKEN_RE.findall(text or ""):
        if t in _STOP:
            continue
        if len(t) == 1 and t.isalpha():
            continue                       # bound variable name
        toks.append(t)
        if "." in t or "_" in t:
            toks.extend(p for p in re.split(r"[._]", t)
                        if p and p not in _STOP
                        and not (len(p) == 1 and p.isalpha()))
    return toks


@dataclass(slots=True)
class Candidate:
    name: str
    kind: str
    statement: str
    module: str
    score: float


class StatementIndex:
    """BM25 over Mathlib STATEMENTS (not names)."""

    __slots__ = ("_docs", "_df", "_len", "_avg", "_n", "_post")

    def __init__(self, docs: list[dict]):
        self._docs = docs
        self._n = len(docs)
        self._df: Counter = Counter()
        self._len: list[int] = []
        self._post: dict[str, list[tuple[int, int]]] = {}
        for i, d in enumerate(docs):
            # The NAME is indexed alongside the statement. Two reasons, both
            # measured: (a) a lemma inside `namespace Finset` writes bare
            # `range`, so a goal written `Finset.range` scored every doc
            # that spells the namespace out ABOVE the lemma actually about
            # it; the name restores that context. (b) statements collapse
            # to very few tokens once bound variables are dropped, so the
            # name's `sum`/`range`/`succ` carry real signal.
            tf = Counter(tokenize(d["statement"]) + tokenize(d["name"]))
            self._len.append(sum(tf.values()) or 1)
            for tok, c in tf.items():
                self._df[tok] += 1
                self._post.setdefault(tok, []).append((i, c))
        self._avg = (sum(self._len) / self._n) if self._n else 1.0

    @classmethod
    def load(cls, path: str | Path) -> "StatementIndex":
        docs = []
        for line in Path(path).read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                try:
                    docs.append(json.loads(line))
                except Exception:
                    pass
        return cls(docs)

    def __len__(self) -> int:
        return self._n

    def search(self, goal: str, k: int = 10,
               kinds: Iterable[str] | None = None) -> list[Candidate]:
        """Top-k declarations whose STATEMENT best matches `goal`."""
        q = tokenize(goal)
        if not q or not self._n:
            return []
        want = set(kinds) if kinds else None
        k1, b = 1.5, 0.75
        scores: Counter = Counter()
        for tok in set(q):
            post = self._post.get(tok)
            if not post:
                continue
            idf = math.log(1 + (self._n - self._df[tok] + 0.5)
                           / (self._df[tok] + 0.5))
            for i, c in post:
                dl = self._len[i]
                scores[i] += idf * (c * (k1 + 1)) / (
                    c + k1 * (1 - b + b * dl / self._avg))
        out: list[Candidate] = []
        for i, s in scores.most_common(k * 5):
            d = self._docs[i]
            if want and d["kind"] not in want:
                continue
            out.append(Candidate(d["name"], d["kind"], d["statement"],
                                 d["module"], round(s, 3)))
            if len(out) >= k:
                break
        return out


# ---- kernel-gated confirmation ---------------------------------------------

#: Ways a retrieved lemma might close a goal, CHEAPEST FIRST. `exact` is
#: near-free; `simpa` runs the simp set and `rw` rewrites then tries rfl,
#: and on a big-operator goal either can cost seconds to minutes.
#: The first four are ZERO-STEP citations: they apply the retrieved lemma
#: to the goal exactly as it stands. That is not enough for a PutnamBench
#: leaf, which routinely (a) is universally quantified, so `rw` cannot
#: reach under the binders, and (b) states its predicate as a HYPOTHESIS
#: BINDER (`cong`, `numform`, `squarish`, `hS`) rather than a definition,
#: so no Mathlib lemma can mention it until that hypothesis is used.
#:
#: `intros; simp only [*, {n}]` covers both generically — `intros` clears
#: the binders and `simp only [*]` picks up the problem's own defining
#: hypothesis by context, never by name — and folds in orientation, so no
#: separate `.symm` form is needed.
#:
#: Measured on the `putnam_1986_b3` `h_cd` leaf (`cong a b m ↔ C m ∣ a-b`,
#: closed by Mathlib's `Polynomial.C_dvd_iff_dvd_coeff`): all four
#: zero-step forms FAIL, this one PASSES. Recognition returned
#: `not_confirmed` on that leaf and the run then spent ~1434 s of 2738 s
#: abducing a replacement for a lemma the pin already carried.
#:
#: The trailing `done` is LOAD-BEARING, not decoration. `first` backtracks
#: on tactic FAILURE, not on unclosed goals, so every alternative must be
#: all-or-nothing. The four zero-step forms are inherently so (`exact`/`rw`
#: either close the goal or fail). `simp only [*, …]` is NOT: fed the wrong
#: candidate it still rewrites with the local hypotheses, SUCCEEDS with the
#: goal open, and `first` commits to it — silently starving every later
#: alternative, including the right one. Observed exactly that: with
#: `Polynomial.coeff_C_mul` ranked ahead of `Polynomial.C_dvd_iff_dvd_coeff`,
#: the ladder stalled on the former with
#:     ⊢ (∀ i, m ∣ (a - b).coeff i) ↔ Polynomial.C m ∣ a - b
#: still open. `done` turns "made progress" back into failure so the ladder
#: keeps walking.
#:
#: It goes LAST and must stay last: `confirm_tactic` iterates forms outer
#: / candidates inner, so position here is the cost ordering, and
#: `simp only [*, …]` is the dearest of the five. Full `simp` in its place
#: FAILS the same leaf (it normalises past the target) as well as costing
#: more — so this is not an oversight to be "improved" later.
_TACTIC_FORMS = ("exact {n}", "exact {n} _ _", "simpa using {n}", "rw [{n}]",
                 "intros; simp only [*, {n}]; done")


def candidate_tactics(name: str) -> list[str]:
    """Ways a retrieved lemma might close a goal it matches.

    `exact` alone is too strict: a retrieved lemma routinely matches only
    up to implicit arguments, a defeq unfolding, an orientation, or a
    binder/hypothesis step the citation cannot perform on its own.
    """
    return [f.format(n=name) for f in _TACTIC_FORMS]


def confirm_tactic(candidates: Iterable[Candidate]) -> str:
    """One tactic that tries every candidate every way.

    ONE compile for the whole recognition step, not one per candidate.
    A compile costs 100-900s on this host, so confirming 8 candidates
    four ways separately would cost 32 compiles and could never run
    inside a real proof attempt.

    Alternatives are ordered BY COST ACROSS CANDIDATES — every `exact`
    first, then every `simpa`, and so on — NOT grouped by candidate.
    Grouping by candidate buries a cheap `exact` on the fourth candidate
    behind nine `simpa`/`rw` elaborations on the first three. Measured:
    with the per-candidate order, the `putnam_2020_a2` reindexing goal
    hit a 1200s timeout even though the right lemma was ranked FIRST, so
    the kernel never got to answer. `first` commits to the earliest
    branch that closes the goal, so this reordering cannot change WHICH
    goals are provable — only how long it takes to find out.

    Every alternative is PARENTHESISED. An unparenthesised `first | …`
    lets a trailing combinator swallow the following bar — the exact bug
    that broke the leaf-fallback ladder earlier in this pipeline.
    """
    cands = list(candidates)
    alts = [f"({form.format(n=c.name)})"
            for form in _TACTIC_FORMS for c in cands]
    if not alts:
        return ""
    return "first\n  | " + "\n  | ".join(alts)


@dataclass(slots=True)
class Recognition:
    """What the kernel accepted, if anything."""
    confirmed: bool
    tactic: str                       # usable proof body when confirmed
    candidates: list[Candidate]


def confirm(goal: str, candidates: Iterable[Candidate], *,
            verify_fn: Callable[[str, str], dict]) -> Recognition:
    """Ask Lean whether ANY retrieved candidate closes `goal`.

    Retrieval only ranks; THIS is what makes a suggestion usable. The
    accepted `first | …` tactic IS a valid Lean proof, so there is no need
    to spend further compiles identifying which alternative won.

    `verify_fn(theorem_header, body)` follows the pipeline convention
    (`run_dag._verify_fn`): IMPORTS ARE THE CLOSURE'S, not ours. Emitting
    an `import` line here placed an import after a declaration and would
    have made every confirmation fail on a syntax error, never on maths.
    """
    cands = list(candidates)
    tac = confirm_tactic(cands)
    if not tac:
        return Recognition(False, "", cands)
    body = "  " + tac.replace("\n", "\n  ")
    try:
        res = verify_fn(f"example : {goal.strip()}", body)
    except Exception:
        return Recognition(False, "", cands)
    return Recognition(bool(res.get("ok")), tac if res.get("ok") else "",
                       cands)


def recognize_for_statement(statement: str, goal: str,
                            index: StatementIndex, *,
                            verify_fn: Callable[[str, str], dict],
                            k: int = 8,
                            trace: Callable[..., None] | None = None
                            ) -> str | None:
    """A tactic Lean accepts as a proof of `statement`, or None.

    Retrieval searches on the GOAL — the conclusion is what identifies a
    lemma, and the binders are noise for ranking. Confirmation, though,
    must use the WHOLE statement: a goal lifted out of its binders has
    unbound variables and would fail to elaborate for reasons that have
    nothing to do with whether the lemma applies.

    One compile, whatever the outcome.
    """
    tr = trace or (lambda kind, **kw: None)
    cands = index.search(goal, k=k, kinds=("theorem", "lemma"))
    if not cands:
        tr("recognize", stage="no_candidates")
        return None
    tac = confirm_tactic(cands)
    body = "  " + tac.replace("\n", "\n  ")
    try:
        res = verify_fn(statement, body)
    except Exception:
        return None
    ok = bool(res.get("ok"))
    tr("recognize", stage="CONFIRMED" if ok else "not_confirmed",
       names=[c.name for c in cands])
    return tac if ok else None


def recognize(goal: str, index: StatementIndex, *,
              verify_fn: Callable[[str, str], dict] | None = None,
              k: int = 8,
              trace: Callable[..., None] | None = None) -> Recognition:
    """Retrieve, then let the kernel decide — at a cost of ONE compile.

    With no `verify_fn` this reports `confirmed=False` rather than an
    unverified guess: an unconfirmed name is exactly the kind of thing
    that has already cost this pipeline whole runs.
    """
    tr = trace or (lambda kind, **kw: None)
    cands = index.search(goal, k=k, kinds=("theorem", "lemma"))
    tr("recognize", stage="retrieved", n=len(cands),
       names=[c.name for c in cands])
    if verify_fn is None or not cands:
        return Recognition(False, "", cands)
    rec = confirm(goal, cands, verify_fn=verify_fn)
    tr("recognize", stage="CONFIRMED" if rec.confirmed else "not_confirmed",
       names=[c.name for c in cands])
    return rec
